#!/usr/bin/env bash

# cd
alias p="cd $PROJECTS"
alias n="cd $ICLOUD/notes"

# shortcuts
alias c='clear'

# trash
alias rm='trash'

# firefox
alias firefox='/Applications/Firefox.app/Contents/MacOS/firefox-bin'

# homebrew
alias brewu='brew update && brew upgrade && brew cleanup && brew doctor'

# lock screen
alias lock='pmset sleepnow'

# nvim
alias vi='nvim'
alias vim='nvim'
