tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "bash"
brew "bruno"
brew "fzf"
brew "git"
brew "jesseduffield/lazygit/lazygit"
brew "mas"
brew "neovim"
brew "node"
brew "ripgrep"
brew "sheldon"
brew "vim"
brew "zoxide"
brew "zsh"

cask "bitwarden"
cask "brave-browser"
cask "docker"
cask "firefox"
cask "flux"
cask "imageoptim"
cask "kitty"
cask "raycast"
cask "rectangle"

# Fonts
cask "font-source-code-pro"
cask "font-symbols-only-nerd-font"
