tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "bash"
brew "git"
brew "mas"
brew "node"
brew "vim"
brew "zsh"

cask "alfred"
cask "bitwarden"
cask "firefox"
cask "flux"
cask "font-fira-code"
cask "google-chrome"
cask "hyper"
cask "imageoptim"
cask "slack"
cask "visual-studio-code"